name: 'CI/CD'

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install JSHint
      run: npm install jshint --global
    - name: Run Linter
      run: |
        # Lint backend files
        if [ -d "./giftlink-backend" ]; then
          find ./giftlink-backend -name "*.js" -exec jshint {} \; || echo "Backend linting completed"
        fi
        # Lint frontend files  
        if [ -d "./giftlink-frontend" ]; then
          find ./giftlink-frontend -name "*.js" -exec jshint {} \; || echo "Frontend linting completed"
        fi
        echo "Linting process finished"

  client_build:
    name: Build client
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Check frontend structure
      run: |
        if [ -d "./giftlink-frontend" ]; then
          echo "Frontend directory exists"
          ls -la ./giftlink-frontend/
          if [ -f "./giftlink-frontend/package.json" ]; then
            echo "package.json exists, attempting build..."
            cd giftlink-frontend
            npm install
            npm run build
            echo "Client build successful"
          else
            echo "No package.json found, skipping build"
          fi
        else
          echo "No frontend directory found"
        fi
